### ISSUE TITLE
apple silicon support

### ISSUE THREAD

**Issue by matti** [jdockerty/kubectl-oomd#9] opened 2022-11-12 16:36 UTC

**Comment by jdockerty** [comment] 2022-11-12 16:45
At the moment for a `darwin_arm64` build, you'll have to run the manual install steps on the `v0.0.4` [releases](https://github.com/jdockerty/kubectl-oomd/releases/download/v0.0.4/oomd_darwin_arm64.tar.gz) page.

If the issue is from a `krew` install, this should hopefully be available soon once I can [fix the checksum problem in the latest index update.](https://github.com/kubernetes-sigs/krew-index/pull/2737) .

**Comment by jdockerty** [comment] 2022-11-15 17:16
As an update to this, the transient checksum issue isn't a problem for the `v0.0.4` release as I've done a bit of extra work to release [`v0.0.5`](https://github.com/kubernetes-sigs/krew-index/pull/2742) and that has passed perfectly fine.

Once this gets merged into the `krew-index`, that'll also include the `darwin_arm64` build for `krew` :blush:

**Comment by jdockerty** [comment] 2022-11-19 17:11
@matti Now that `v0.0.5` has been merged to the `krew-index` this includes a `darwin_arm64` build.

I'll close this as completed, although let me know if you have any issues 😊

**Closed by jdockerty** 2022-11-19 17:11 UTC
